// This file was generated by RedwoodJS
import { RouteParams, QueryParams } from '@redwoodjs/router'
import { A } from 'ts-toolbelt'


declare module '@redwoodjs/router' {
  interface AvailableRoutes {
    // Only "<Route />" components with a "name" and "path" prop will be populated here.
    newPost: (params?: RouteParams<"/posts/new"> & QueryParams) => "/posts/new"
    editPost: (params?: RouteParams<"/posts/{id:Int}/edit"> & QueryParams) => "/posts/{id:Int}/edit"
    post: (params?: RouteParams<"/posts/{id:Int}"> & QueryParams) => "/posts/{id:Int}"
    posts: (params?: RouteParams<"/posts"> & QueryParams) => "/posts"
    newNicolaPost: (params?: RouteParams<"/nicola-posts/new"> & QueryParams) => "/nicola-posts/new"
    editNicolaPost: (params?: RouteParams<"/nicola-posts/{id:Int}/edit"> & QueryParams) => "/nicola-posts/{id:Int}/edit"
    nicolaPost: (params?: RouteParams<"/nicola-posts/{id:Int}"> & QueryParams) => "/nicola-posts/{id:Int}"
    nicolaPosts: (params?: RouteParams<"/nicola-posts"> & QueryParams) => "/nicola-posts"
    newProjectData: (params?: RouteParams<"/project-datas/new"> & QueryParams) => "/project-datas/new"
    editProjectData: (params?: RouteParams<"/project-datas/{id:Int}/edit"> & QueryParams) => "/project-datas/{id:Int}/edit"
    projectData: (params?: RouteParams<"/project-datas/{id:Int}"> & QueryParams) => "/project-datas/{id:Int}"
    projectDatas: (params?: RouteParams<"/project-datas"> & QueryParams) => "/project-datas"
    client: (params?: RouteParams<"/client"> & QueryParams) => "/client"
    blogAdmin: (params?: RouteParams<"/blog-admin"> & QueryParams) => "/blog-admin"
    developer: (params?: RouteParams<"/developer"> & QueryParams) => "/developer"
    signup: (params?: RouteParams<"/signup"> & QueryParams) => "/signup"
    contactus: (params?: RouteParams<"/contactus"> & QueryParams) => "/contactus"
    home: (params?: RouteParams<"/"> & QueryParams) => "/"
    about: (params?: RouteParams<"/about"> & QueryParams) => "/about"
    login: (params?: RouteParams<"/login"> & QueryParams) => "/login"
    nicolasBlog: (params?: RouteParams<"/nicolas-blog"> & QueryParams) => "/nicolas-blog"
    aaronsBlog: (params?: RouteParams<"/aarons-blog"> & QueryParams) => "/aarons-blog"
    forgotPassword: (params?: RouteParams<"/forgot-password"> & QueryParams) => "/forgot-password"
    resetPassword: (params?: RouteParams<"/reset-password"> & QueryParams) => "/reset-password"
  }
}

