// This file was generated by RedwoodJS
import AaronsArticlePageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/AaronsArticlePage/AaronsArticlePage'
import AaronsBlogPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/AaronsBlogPage/AaronsBlogPage'
import AboutPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/AboutPage/AboutPage'
import BlogAdminPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/BlogAdminPage/BlogAdminPage'
import ClientPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/ClientPage/ClientPage'
import ContactusPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/ContactusPage/ContactusPage'
import DeveloperPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/DeveloperPage/DeveloperPage'
import FatalErrorPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HomePageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/HomePage/HomePage'
import LoginPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/LoginPage/LoginPage'
import NicolasArticlePageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/NicolasArticlePage/NicolasArticlePage'
import NicolasBlogPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/NicolasBlogPage/NicolasBlogPage'
import NotFoundPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/NotFoundPage/NotFoundPage'
import ResetPasswordPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import SignupPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/SignupPage/SignupPage'
import NicolaPostEditNicolaPostPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/NicolaPost/EditNicolaPostPage/EditNicolaPostPage'
import NicolaPostNewNicolaPostPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/NicolaPost/NewNicolaPostPage/NewNicolaPostPage'
import NicolaPostNicolaPostPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/NicolaPost/NicolaPostPage/NicolaPostPage'
import NicolaPostNicolaPostsPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/NicolaPost/NicolaPostsPage/NicolaPostsPage'
import PostEditPostPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/Post/EditPostPage/EditPostPage'
import PostNewPostPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/Post/NewPostPage/NewPostPage'
import PostPostPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/Post/PostPage/PostPage'
import PostPostsPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/Post/PostsPage/PostsPage'
import ProjectDataEditProjectDataPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/ProjectData/EditProjectDataPage/EditProjectDataPage'
import ProjectDataNewProjectDataPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/ProjectData/NewProjectDataPage/NewProjectDataPage'
import ProjectDataProjectDataPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/ProjectData/ProjectDataPage/ProjectDataPage'
import ProjectDataProjectDatasPageType from '/home/aaron/Desktop/Redwood Expanion/Expansion/web/src/pages/ProjectData/ProjectDatasPage/ProjectDatasPage'

declare global {
  const AaronsArticlePage: typeof AaronsArticlePageType
  const AaronsBlogPage: typeof AaronsBlogPageType
  const AboutPage: typeof AboutPageType
  const BlogAdminPage: typeof BlogAdminPageType
  const ClientPage: typeof ClientPageType
  const ContactusPage: typeof ContactusPageType
  const DeveloperPage: typeof DeveloperPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NicolasArticlePage: typeof NicolasArticlePageType
  const NicolasBlogPage: typeof NicolasBlogPageType
  const NotFoundPage: typeof NotFoundPageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const SignupPage: typeof SignupPageType
  const NicolaPostEditNicolaPostPage: typeof NicolaPostEditNicolaPostPageType
  const NicolaPostNewNicolaPostPage: typeof NicolaPostNewNicolaPostPageType
  const NicolaPostNicolaPostPage: typeof NicolaPostNicolaPostPageType
  const NicolaPostNicolaPostsPage: typeof NicolaPostNicolaPostsPageType
  const PostEditPostPage: typeof PostEditPostPageType
  const PostNewPostPage: typeof PostNewPostPageType
  const PostPostPage: typeof PostPostPageType
  const PostPostsPage: typeof PostPostsPageType
  const ProjectDataEditProjectDataPage: typeof ProjectDataEditProjectDataPageType
  const ProjectDataNewProjectDataPage: typeof ProjectDataNewProjectDataPageType
  const ProjectDataProjectDataPage: typeof ProjectDataProjectDataPageType
  const ProjectDataProjectDatasPage: typeof ProjectDataProjectDatasPageType
}
