// This file was generated by RedwoodJS
import * as Cell from './ProjectDatasCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindProjectDatas, FindProjectDatasVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProjectDatasCell'

type CellInputs = CellProps<SuccessType, FindProjectDatas, typeof Cell, FindProjectDatasVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
