// This file was generated by RedwoodJS
import * as Cell from './LikeButtonCell'
import type { CellProps } from '@redwoodjs/web'
import type { any, any } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './LikeButtonCell'

type CellInputs = CellProps<SuccessType, any, typeof Cell, any>

export default function (props: CellInputs): ReturnType<SuccessType>
